services:
  db:
    image: mysql:latest
    container_name: sv-app-mysql
    ports:
      - "3306:3306"
    env_file:
      - ../.env
    volumes:
      - /var/docker/svapp/data/mysql:/var/lib/mysql #change to correct path
    networks:
      - db_network
  sv-app:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    container_name: sv-app
    #ports:
      #- "80:8080"
    env_file:
      - ../.env
    networks:
      - caddy
      - db_network
    labels:
      caddy: svapp.iss.tuhh.de
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: /certs/svapp/cert.pem /certs/svapp/cert.key
    depends_on:
      - db

networks:
  caddy:
    external: true
  db_network: